supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
    - arm64

overrides:
  nanoid: 3.3.18

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
